const GET_DMS_VERSION_HISTORY_PENDING = 'GET_DMS_VERSION_HISTORY_PENDING';
const GET_DMS_VERSION_HISTORY_SUCCESS = 'GET_DMS_VERSION_HISTORY_SUCCESS';
const GET_DMS_VERSION_HISTORY_REJECTED = 'GET_DMS_VERSION_HISTORY_REJECTED';

/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  GET_DMS_VERSION_HISTORY_PENDING,
  GET_DMS_VERSION_HISTORY_SUCCESS,
  GET_DMS_VERSION_HISTORY_REJECTED,
};
