const REMOVE_DMS_FILE_UPLOAD = 'REMOVE_DMS_FILE_UPLOAD';
const DMS_FILE_UPLOAD = 'DMS_FILE_UPLOAD';
const DMS_FILE_UPLOAD_RESET = 'DMS_FILE_UPLOAD_RESET';

const MODAL_SHOW = 'MODAL_SHOW';
const MODAL_HIDE = 'MODAL_HIDE';
const SET_DMS_CONTEXT = 'SET_DMS_CONTEXT';

const UPDATE_FILE_NAME = 'UPDATE_FILE_NAME';

/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  REMOVE_DMS_FILE_UPLOAD,
  DMS_FILE_UPLOAD,
  MODAL_SHOW,
  MODAL_HIDE,
  SET_DMS_CONTEXT,
  DMS_FILE_UPLOAD_RESET,
  UPDATE_FILE_NAME,
};
